/* 
 * Swagger Generator
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 2.2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ServersApiTests
    {
        private ServersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ServersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ServersApi
            //Assert.IsInstanceOfType(typeof(ServersApi), instance, "instance is a ServersApi");
        }

        
        /// <summary>
        /// Test DownloadFile
        /// </summary>
        [Test]
        public void DownloadFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fileId = null;
            //var response = instance.DownloadFile(fileId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GenerateServerForLanguage
        /// </summary>
        [Test]
        public void GenerateServerForLanguageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string framework = null;
            //Body1 body = null;
            //var response = instance.GenerateServerForLanguage(framework, body);
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test GetServerOptions
        /// </summary>
        [Test]
        public void GetServerOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string framework = null;
            //var response = instance.GetServerOptions(framework);
            //Assert.IsInstanceOf<Dictionary<string, InlineResponse200>> (response, "response is Dictionary<string, InlineResponse200>");
        }
        
        /// <summary>
        /// Test ServerOptions
        /// </summary>
        [Test]
        public void ServerOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ServerOptions();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
    }

}
