/* 
 * Swagger Generator
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 2.2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GeneratorInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeneratorInputTests
    {
        // TODO uncomment below to declare an instance variable for GeneratorInput
        //private GeneratorInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeneratorInput
            //instance = new GeneratorInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeneratorInput
        /// </summary>
        [Test]
        public void GeneratorInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeneratorInput
            //Assert.IsInstanceOfType<GeneratorInput> (instance, "variable 'instance' is a GeneratorInput");
        }

        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Test]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'SwaggerUrl'
        /// </summary>
        [Test]
        public void SwaggerUrlTest()
        {
            // TODO unit test for the property 'SwaggerUrl'
        }
        /// <summary>
        /// Test the property 'AuthorizationValue'
        /// </summary>
        [Test]
        public void AuthorizationValueTest()
        {
            // TODO unit test for the property 'AuthorizationValue'
        }
        /// <summary>
        /// Test the property 'SecurityDefinition'
        /// </summary>
        [Test]
        public void SecurityDefinitionTest()
        {
            // TODO unit test for the property 'SecurityDefinition'
        }

    }

}
